### ISSUE TITLE
Space between tabs in application details page 

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#111]
## Bug description

Space between tabs in application details page is uneven (Screenshot attached)

## Expected behavior
The space between tabs should be uniform

## How to reproduce

1. Go to applications page by clicking Metrics tab on the left column
2. Click any service to go to service details page
3. The space between "Application Metrics" and "External Calls" tab is uneven

## Additional context

![photo_2021-05-22 18 39 23](https://user-images.githubusercontent.com/504541/119227814-6b1e4380-bb2d-11eb-958f-1cc31792f160.jpeg)

**Comment by rbrishabh** [comment]
Hello @pranay01 ! I can help with this one! I have set up signoz locally (I'll also ask my company to possibly migrate from dd to signoz!) but Im not sure how to add an application locally! is there any documentation for that?

**Comment by ankitnayan** [comment]
@rbrishabh the installation of SigNoz comes with a few applications already sending data to SigNoz. Ping me on `#contributing` channel on slack. We have a much simpler setup for frontend development. Since frontend runs as an independent unit, it just needs the URL of the query-service API to work. Will send instructions in slack.

**Comment by ankitnayan** [comment]
@rbrishabh the installation of SigNoz comes with a few applications already sending data to SigNoz. 

What do you mean by `add an application locally`? Do you want to add more applications? You can refer to [docs](https://signoz.io/docs/instrumentation/nodejs) for instrumenting. 

Though, I don't think you need to set up a new application for fixing this issue.

We can discuss more on `#contributing` channel on slack. We have a much simpler setup for frontend development. Since the frontend runs as an independent unit, it just needs the URL of the query-service API to work. Will send instructions in slack.

**Comment by saideepesh000** [comment]
@rbrishabh , r u still interested in working on this ?

**Comment by rbrishabh** [comment]
Hello! Unfortunately I don't have much free time, so please feel free to take this up!

**Comment by saideepesh000** [comment]
Hey @pranay01 @ankitnayan , I think this fixed, can u check and confirm it, so that we can close this issue.
![image](https://user-images.githubusercontent.com/43727167/126897652-8b30c1c7-3578-4c27-8305-655787acc981.png)

**Comment by pranay01** [comment]
@saideepesh000 Ok, let me check

**Comment by pranay01** [comment]
Yeah, this issue seems fixed. Thanks for pointing out @saideepesh000 👍 
 Closing this issue
