### ISSUE TITLE
How to set signoz-access-token?

### ISSUE THREAD

**Issue by GameXG** [SigNoz/signoz#1200]
The [sample-golang-app](https://github.com/SigNoz/sample-golang-app) example sets [signoz-access-token](https://github.com/SigNoz/sample-golang-app/blob/master/main.go#L33) , where can signoz get this token?

How does signoz add client authentication? Only process legally submitted data?

**Comment by pranay01** [comment]
@GameXG I don't think you need SigNoz access token. @makeavish can you confirm this? Please remove it from sample token as well if it is not needed

@GameXG What do you mean by client authentication? Do you want to check if the application sending data to SigNoz is authenticated to send or not?

**Comment by makeavish** [comment]
Yes @pranay01 signoz access token is not required, it's mentioned in [blog](https://signoz.io/opentelemetry/go/) too.

**Comment by pranay01** [comment]
I see. Can you raise PR fixing both the blog and the sample app @makeavish

**Comment by GameXG** [comment]
thanks 

@pranay01  Yes, hopefully only authenticated programs can send data to SigNoz.

**Comment by klkvsk** [comment]
Hijacking this discussion since it is the first result on googling signoz self-hosted ingestion token auth.

If you want to secure your otel ingestion, add an [authentication mechanism](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configauth/README.md) manually to signoz-otel-collector in deploy/docker/otel-collector-config.yaml:
1. add to "extensions:"
```
  bearertokenauth:
    token: "YOURTOKEN"
```

2. add to "services: extensions:" 
`    - bearertokenauth`

4. add to "receivers: grpc:" and "http:":
```
        auth:
          authenticator: bearertokenauth
```

Now your app should be configured with `OTEL_EXPORTER_OTLP_HEADERS=Authorization=Bearer YOURTOKEN`

You'd probably want to add tls as well if you're exposing the collector.
