### ISSUE TITLE
Alert expression support for exceptions

### ISSUE THREAD

**Issue by kenichi** [SigNoz/signoz#1222]
## Is your feature request related to a problem?

We can not get alerts configured for quantity of exceptions (>0) in a time range.

## Describe the solution you'd like

We'd like to have an expression or built-in metric to count exceptions in a time range so that we may trigger an alert when conditions are met.

## Describe alternatives you've considered

sentry, rollbar, honeybadger, etc.

## Additional context

https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1654115071018679

#### *Thank you* for your feature request – we love each and every one! 

<3

**Comment by srikanthccv** [comment]
@kenichi Are you sending any exception counter metric to signoz? If so, you could create your own expression on that metric  for rule.

Otherwise, you can use one of metrics generated by signoz from the span data and relevant metric is `signoz_calls_total`. You could probably use this metric. Expression for rule would look something like this for error rate change > x% for 1 min.

```
sum(rate(signoz_calls_total{http_status_code=~"^5.."}[1m])) / sum(rate(signoz_calls_total[1m])) * 100 > x
```

You could add more filter criteria such as `service_name`, `operation` etc...

**Comment by pranay01** [comment]
hey @kenichi Just curious, don't platform like Sentry/Rollbar allow you to set such alerts. Asking as I don't have much experience with these platforms :)

**Comment by makeavish** [comment]
We have added feature to set alerts on exceptions using clickhouse query:
<img width="1420" alt="Screenshot 2023-01-20 at 09 01 33" src="https://user-images.githubusercontent.com/9512100/213611883-3a1c8723-42e5-44be-a6cf-652be6fd422e.png">

Closing this issue.
