### ISSUE TITLE
Show pub/sub and cron services in Services list

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1442]
_Description of the problem_
Currently Services list tab only shows services which serve API requests, though many users have services which are Pub/Sub services or cron jobs. Currently these services are not shown in services list

_Expected Behavior_
Pub/sub and cron job services should also be shown in services list and the top level metrics like p99 latency, RPS and Error rates be shown for them.

**Comment by srikanthccv** [comment]
@ankitnayan running a background job to fetch traces and compute top-level operations is an overkill for this. I think we are fine with just using views. It will be something like this
```
CREATE TABLE IF NOT EXISTS signoz_traces.top_level_operations (
    name LowCardinality(String) CODEC(ZSTD(1)),
    serviceName LowCardinality(String) CODEC(ZSTD(1))
) ENGINE MergeTree()
ORDER BY (serviceName, name);

CREATE MATERIALIZED VIEW IF NOT EXISTS signoz_traces.sub_root_operations
TO signoz_traces.top_level_operations
AS SELECT DISTINCT
    name,
    serviceName
FROM signoz_index_v2 AS A, signoz_index_v2 AS B
WHERE (A.serviceName != B.serviceName) AND (A.parentSpanID = B.spanID);

CREATE MATERIALIZED VIEW IF NOT EXISTS signoz_traces.root_operations
TO signoz_traces.top_level_operations
AS SELECT DISTINCT
    name,
    serviceName
FROM signoz_index_v2
WHERE parentSpanID = '';
```

There are no changes needed from metrics since the `calls_total` and `call_latency` metrics also have `operation` in the label set. Please let me know if you prefer some other approach.
