### ISSUE TITLE
API (and documentation) on how to monitor processors that request data from a job queue

### ISSUE THREAD

**Issue by drjasonharrison** [SigNoz/signoz#1584]
## Is your feature request related to a problem?

No

## Describe the solution you'd like

We would like to monitor processors that request data from a job queue. The jobs (JSON data) arrive from outside of the system and are queued based on the values of fields within the request. Since it's JSON, our queue system puts the jobs into sub-queues. Then a processor will request a job from the sub-queue and process it, finally telling the queue that the job was processed correctly or "completed" or there was an inherent problem with the data and the job should be recorded as "failed".

The processor can be instrumented with Open Telemetry to report on the end of job result and processing time.

We'd like to be able to send these events through Open Telemetry, have SigNoz display them on a dashboard, and then query them by a separate processor scaler to determine if we should scale the number of processors up and down.

Again, the processing time data 
- originate at the processors, 
- are emitted as Open Telemetry events,
- transported via Open Telemetry, 
- collected by Open Telemetry Collector 
- [something]
- query by the scaling processor

## Describe alternatives you've considered

We have a separate process that checks the queue for the number of jobs for each sub-system and then directs AWS ECS and ECS to increase or decrease the number of jobs. We'd like to use more precise data such as the average or 90 percentile job processing time.

Knowing how to query the summarized statistics from the SigNoz deployment would be very helpful.

## Additional context

Often processing pipelines have various stages that either push or pull data along them. We have jobs being pushed on the queue and then the processors pull the jobs from the queue. We don't have access to a trace that says "this is how long this request required" from the perspective of the queue because the processor doesn't hold open the connection, though it does report back which job identifier it finished processing.

We're also trying to be cloud provider agnostic as possible, thus we use our own queue rather than anything from AWS/Azure/Google that might already support automatic scaling.

#### *Thank you* for your feature request – we love each and every one!

**Comment by srikanthccv** [comment]
@drjasonharrison What I understand from your description is that you have piece of program that consumes a message from queue and does some work and at the end conditionally marks if the job failed. And you would like to monitor this setup, right?

It seems you only have one hop which is the processor program. You will probably need to manually instrument the processor code depending upon the code and queue client library you are using and send the data to SigNoz as you would already be sending for other applications. 

There are two ways you can send the data to SigNoz for this use case.
 
1. Emit gauge measurements with processing time
2. Start a trace and create a span that records the processing duration

Depending on your preferred choice you will have to query different data source in SigNoz. I would personally pick sending gauge values because a trace would have made more sense if the message goes through series of producers and consumers tracking the start time and duration etc... but again it's up to you how you want to send the data.

Once you have sent the telemetry to SigNoz you could use Our query builder https://signoz.io/docs/userguide/create-a-custom-query/ or ClickHouse query tab to write your own SQL queries that query data.

If you were to send the gauge measurements, you would pick the relevant PXX from [aggregate operator](https://signoz.io/docs/userguide/create-a-custom-query/#supported-aggregation-functions) with the metric name you give may be something like `job_processor_time` And optionally apply filters. This will chart the plot with x percentile for the processor duration.

<img width="817" alt="Screenshot 2022-09-22 at 1 09 16 PM" src="https://user-images.githubusercontent.com/22846633/191687053-ba374e72-fa9b-45e7-925e-c059574fef7d.png">


If you were to send the gauge measurement, and you would like to use the ClickHouse query option writing your own sql queries. The query you write should result in one column with time.Time type, value with float64 type, and optional number of string column if there is some group by. The query would look like following if you are looking for p90 of `my_processor_time` for a resolution of minute for the metric for last thirty minutes.

```sql
SELECT quantile(0.9)(value), toStartOfInterval(toDateTime(intDiv(timestamp_ms, 1000)), toIntervalSecond(60)) AS ts
FROM signoz_metrics.samples_v2
WHERE (metric_name = 'my_processor_time') AND (timestamp_ms > (toUnixTimestamp(now() - toIntervalMinute(30)) * 1000))
GROUP BY ts
```

If you were to send the data with traces where a span in the trace indicates the processor time, then the query would look like following.

```sql
SELECT
    toDateTime(toStartOfMinute(timestamp)) AS ts,
    quantile(0.9)(durationNano)
FROM signoz_traces.signoz_index_v2
WHERE timestamp > toDateTime64(now() - toIntervalMinute(30), 0, 'UTC') and name='my_processor_time'
GROUP BY ts
ORDER BY ts ASC
```

If you just want the only for total duration then select the resolution granularity same the query interval. This will enable you to plot the pXX using dashboards.


There is no open API for you get this data as of now. You may look the at the current API SigNoz UI uses (`api/v2/metrics/query_range`) to fetch the data and use it. This endpoint requires authentication so you will have to keep that in mind as well.

**Comment by drjasonharrison** [comment]
Thank you!
