### ISSUE TITLE
Upgrade clickhouse to 22.8

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#1618]
Clickhouse version needs to be updated to 22.8 LTS version as it also fixes the issues with sorting in projections.

**Comment by ankitnayan** [comment]
@srikanthccv we also have a couple of other improvements with version 22.8, anything blocking moving?

@prashant-shahi can we test this with upgrading signoz and test data sanity?

**Comment by srikanthccv** [comment]
This was the issue I was referring to https://altinity.com/blog/possible-clickhouse-data-corruption-advisory. We are using `AggregatingMergeTree` for the service map, but the issue shouldn't be affecting since we don't have a function that sore string for aggregation. I don't see anything else blocking us from upgrading.

**Comment by ankitnayan** [comment]
cool..then let's go
