### ISSUE TITLE
Add support for linked spans in the UI

### ISSUE THREAD

**Issue by joosthooz** [SigNoz/signoz#1767]
## Is your feature request related to a problem?

Linked spans https://opentelemetry.io/docs/reference/specification/overview/#links-between-spans are a way to create a connection between spans, other than parent/child. This way, a span can link to another span in the current, or inside another trace. The signoz collector does store the link into the database: https://github.com/SigNoz/signoz-otel-collector/blob/6a0b4aea8f9bbd8c12499043d19ad517c542490b/exporter/clickhousetracesexporter/clickhouse_exporter.go#L61 but the UI does not show them.

## Describe the solution you'd like
The UI could add a clickable button to a span's properties. As example, Jaeger places a button next to the span name:
![image](https://user-images.githubusercontent.com/1442581/204273041-59c8ac2b-afb5-4167-9a22-4472ea7bcaae.png)
It would be nice if the link would open a new trace viewer (in a new tab for example) focusing on that target. Maybe even with a brief summary of where it was linked from (like the path to the root of the source span)

## Additional context
The link is added to the `references` list in the `model` column of the signoz_spans table:
`select JSONExtractString(model, 'references') from signoz_traces.signoz_spans where traceID = '21e159089d67352faa5d8d3869c509f0'` results in: 
```
[{"traceId":"21e159089d67352faa5d8d3869c509f0","spanId":"5ba0f14cb795e20a","refType":"CHILD_OF"},{"traceId":"88b45d50729955cfc5b5e090c62d69c5","spanId":"0748bc36162b0b9d","refType":"FOLLOWS_FROM"}]
[{"traceId":"21e159089d67352faa5d8d3869c509f0","spanId":"7dc3bd0a42b64cc0","refType":"CHILD_OF"}]
...
```
Where the 1st row has a linked span, and the 2nd does not.

#### *Thank you* for your feature request – we love each and every one!

**Comment by pranay01** [comment]
@joosthooz Would it be possible to create a short screen recording of how the linked span experience words in Jaeger and share here. Would give us a better idea of the current behavior in Jaeger.

Also, if a span has multiple linked spans, how is it shown in Jaeger UI currently? The screenshot you have shared seems to link to only 1 other span

**Comment by pranay01** [comment]
One possible area for us to show the linked spans is the right attribute panel

_Linked spans showing last 8 digits of span id and hyperlink click opens it in another tab - in trace detail view_
![gantt-expanded-more](https://user-images.githubusercontent.com/504541/205079012-5848a78f-45f8-47f0-b999-e375e0357bed.png)

**Comment by makeavish** [comment]
@pranay01 Here's an example loom video of spanLinks on jaeger which I have created https://www.loom.com/share/26ef467d9bed441b81aa434bd1eb9461

**Comment by chris-pinola-rf** [comment]
Also I wanted to point out that, at least as of SigNoz v0.15.0, linked spans currently appear as _missing_ spans. Which is misleading because the referenced span does indeed exist, it is just simply associated with another trace.

![image](https://user-images.githubusercontent.com/87080398/221645840-c27e6111-9505-4086-addd-945a9e456ae9.png)

For additional context, the pictured span was created with the following code:
```kotlin
val span = tracer.spanBuilder("Publish")
    .setSpanKind(SpanKind.PRODUCER)
    .addLink(upstreamSpanContext)
    .startSpan()

try {
  // ...
} finally {
  span.end()
}
```

By the time this span ended, the entire trace/all spans associated with the `upstreamSpanContext` had already finished.

**Comment by pranay01** [comment]
@makeavish can you check the above note by @chris-pinola-rf

**Comment by makeavish** [comment]
@chris-pinola-rf It's reporting as missing span because there's no root span for the `Publish` span. As new span just has `follows from` relationship with upstream span.

**Comment by makeavish** [comment]
@chris-pinola-rf Is it possible for you to share trace json by checking API call?
Please retract any private data.

**Comment by chris-pinola-rf** [comment]
> As new span just has `follows from` relationship with upstream span.

I don't think that's the case though.

_NOTE: I'm using a different example span below compared to my previous comment due to our short data retention policy._

That `Publish` span should be the root span for an entirely separate trace. Inspecting the result of the `/api/v1/traces` call seems to confirm this (note the presence of two links: `CHILD_OF` _and_ `FOLLOWS_FROM`):

```json
[
    {
        "columns": [
            "__time",
            "SpanId",
            "TraceId",
            "ServiceName",
            "Name",
            "Kind",
            "DurationNano",
            "TagsKeys",
            "TagsValues",
            "References",
            "Events",
            "HasError"
        ],
        "events": [
            [
                1677770387870,
                "dd4215947d827228",
                "9bf219f838ef8b0463d64dff0504d9b2",
                "my-service-name",
                "Publish",
                "4",
                "8816124",
                ["omitted..."],
                ["omitted..."],
                [
                    "{TraceId=9bf219f838ef8b0463d64dff0504d9b2, SpanId=, RefType=CHILD_OF}",
                    "{TraceId=801097538749bf86e6f92d6a334a63a7, SpanId=2acca23ab5abc32d, RefType=FOLLOWS_FROM}"
                ],
                [],
                false
            ]
        ]
    }
]
```

Here's how it appears in the UI:

![image](https://user-images.githubusercontent.com/87080398/222473574-2c2a7ab4-d0ff-464c-a6e4-72450ba866a9.png)

Some additional context: in this case the upstream/linked span produces a message to a queue, and then the upstream trace entirely finishes. Sometime unknown amount of time later, the downstream `Publish` operation reads the produced message from the queue and resumes processing. A link seemed like the most appropriate way to model this causal relationship.
