### ISSUE TITLE
Move `Key operations table` and `Latency graph` APIs to metrics

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#1793]
In Service Page, we are currently using traces data to fetch `Key operations table` and `Latency graph`. 
When traces are sampled at the collector level, these metrics gets affected. If we create these metrics using spanToMetrics processor, then we can support sampling at collector level.

**Comment by srikanthccv** [comment]
@palashgdev, will you be able to pick this up? I will share the sample payload for both.

**Comment by srikanthccv** [comment]
I have added a collector for the relevant API calls here using metrics https://signoz.postman.co/workspace/Team-Workspace~cfa5c7b5-124f-4bbc-88d9-2351af8dd95b/collection/21397560-d4426117-8603-4e56-b809-37870a52d18f?action=share&creator=21397560. 

For Latency graph:

We need to make a `query_range` request, one for each p50, p95, and p99 with panelType as `graph` and aggregate operator as `hist_quantile_p{50,95,99}`. The WHERE clause part is the same as other graphs, i.e. `service_name IN ...` and `operation IN ...` and additional such as resource attributes filtering. The unit of returned data is milliseconds. 

For Key Operations:

We need to make a `query_range` request, one for each P50, p95, p99, Num Calls, Error rate with panelType as `table` and `hist_quantile_p{50,95,99}` for PXX and `sum_rate` for Num calls and Error rate. There will be a small change in the WHERE clause part; we should remove the `operation IN ...` part because the idea of this table is to show all operations, not just top-level operations. The Num Calls and Error rate queries will use the formula -- The query for Num Calls returns a per-second value, so for total calls, we need to multiply it by the selected duration in seconds. For instance, if the selected duration is 30 minutes, the formal expression will be `A*1800`, and for 1 hour, it should be `A*3600`. The error rate follows the regular rate payload structure without the `operation IN ...` part of the WHERE clause. The unit of error rate is a percentage from 0-100.


Services List:

We need to get the top-level operation for all services and use it to get the data for the next set of requests. We need to make a `query_range` call for each service and operation, one for each P99, Error rate, and Ops with panelType as a `table`. The WHERE clause will contain the `service_name IN ...` and `operation IN ...` and any additional resource attributes filtering. The units are millis, percentage (0-100), and op/s. 


The collection has examples of all of the above. Please go through them once. It will give some overview. We can hop on a call to discuss it further and clarify any questions/concerns.

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/pull/3188
https://github.com/SigNoz/signoz/pull/3172
