### ISSUE TITLE
On firefox, in gantt chart view, icon before span appears as vertical icon instead of + 

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#186]
## Bug description

On firefox, in gantt chart view, icon before span appears as vertical icon instead of + 

## Expected behavior
Collapsed spans should have + icon before them

## How to reproduce

1. Go to trace page in firefox
2. Click any span from trace list
3. Go to gantt chart view by scrolling down

## Version information 
* **Signoz version**: 0.3.2
* **Browser version**: 89.0.1 (64-bit)
* **Your OS and version**: Mac OS Catalina, version 10.15.7 (19H15)

## Additional context

![Screenshot 2021-06-24 at 11 36 19 PM](https://user-images.githubusercontent.com/504541/123312086-7fe36200-d545-11eb-9e95-3b7ea5ba9de0.jpg)

**Comment by Vimalraj571** [comment]
### About the Issue:
Hi @pranay01 i have gone through this Issue and dug up found following

### Fix 1: 
update antd from  **_4.6.2 to 4.16.7_** 
Actually People from Ant fixed the issue here
[Table row expanded icon disappears when expanded on Firefox and looks like a checkbox](https://github.com/ant-design/ant-design/issues/29303) 

_or_

### Fix 2:
By following code (we can fix this ant 4.6.2 version itself) haven't tried yet in my local dev front-end
[Fix in CSS itself](https://github.com/ant-design/ant-design/issues/29303#issuecomment-814765368)

We can proceed forward!

**Comment by pranay01** [comment]
Thanks @Vimalraj571 for researching on the issue.

@nidhi-tandon @jyash97  - Your thoughts on which approach we should take?

**Comment by pranay01** [comment]
fixed by https://github.com/SigNoz/signoz/pull/764 - Updated trace detail page design
