### ISSUE TITLE
Correlate Logs, Metrics and Traces in Single UI

### ISSUE THREAD

**Issue by spanhotra** [SigNoz/signoz#1995]
Hi Team,

The tool is pretty neat and useful. 
I want to understand how I can have 3 components and correlate them together.

My visualization strategy

- From Traces, and drill into logs for the selected service and have it unified in one component.

**Comment by pranay01** [comment]
@spanhotra Thanks for opening the issue. We are working on including better correlation across different signals.

In the use case you have described, as I understand you want to filter logs for particular services. Can you share more details on the use case? Why would you want to start this from Traces page rather than just filtering based on services in the logs page? Are there some steps you want to do in the traces page first before going to logs page?

**Comment by spanhotra** [comment]
Hi @pranay01 Thanks for the response.
My use case is as follows.
I have multiple services which are calling each other very frequently, Service A -> Service B

One request from has failed out of 50 instances, 
I got to know about the instance via Trace Information, now I have Trace ID for that instance, I can go to the logs, filter via this trace ID and service name to have the relevant logs only.

It would be nice if these filters are auto applied by the tools itself.

Eg, Skywalking does that across Tabs in their service section, Grafana does that using Labels as filters.

**Comment by makeavish** [comment]
Trace -> Logs and metrics correlation is available so this issue can be closed
