### ISSUE TITLE
When viewing some spans, the HTML page does not display anything, and the whole page is black.

### ISSUE THREAD

**Issue by GameXG** [SigNoz/signoz#2128]
## Bug description

![image](https://user-images.githubusercontent.com/457902/214846078-de0143db-2d33-4081-b84c-88757f1c6b34.png)

![image](https://user-images.githubusercontent.com/457902/214846509-e2ad2476-9828-4dc3-bd5e-2dea6fd2f663.png)

## Expected behavior

Normal display

## How to reproduce

Some span hits can cause this problem.

Suspect that these spans may link to other spans?

## Version information 
* **Signoz version**:v0.12.0
* **Browser version**:chrome 109.0.5414.75
* **Your OS and version**: windows 10
* **Your CPU Architecture**(ARM/Intel): amd64

**Comment by pranay01** [comment]
@GameXG Thanks for opening the issue.

Can you add more details on what type of spans are these? Also, we have fixed some similar issues which happen because of missing spans in a trace. Can you update to latest version of SigNoz 0.14.0 and try that.

Also, if you are running SIgNoz on windows, it is not [officially supported](https://signoz.io/docs/install/docker/#prerequisites). Can you try running in a linux machine or mac?
