### ISSUE TITLE
Error Percentage always 100%

### ISSUE THREAD

**Issue by eugene-chernyshenko** [SigNoz/signoz#2291]
## Bug description

Error Percentage always show 100% in the overview
But real error percentage is 15 %
Services list and external call show Error Percentage correctly

<img width="615" alt="Screenshot 2023-02-19 at 02 29 33" src="https://user-images.githubusercontent.com/53478755/219904092-c5c60590-fff6-4f54-8994-d71866e1be99.png">
<img width="608" alt="Screenshot 2023-02-19 at 02 29 42" src="https://user-images.githubusercontent.com/53478755/219904095-50546afd-c7e1-4e18-b6d7-d163fc7fa790.png">
<img width="1240" alt="Screenshot 2023-02-19 at 02 29 57" src="https://user-images.githubusercontent.com/53478755/219904096-c4b0a978-d84e-4a55-b801-3c6469118203.png">

**Comment by eugene-chernyshenko** [comment]
Also service map doesn't show percentage correctly
I got 0.15% instead of 15 %

<img width="328" alt="Screenshot 2023-02-19 at 02 38 10" src="https://user-images.githubusercontent.com/53478755/219904293-6a701a49-0d3b-4429-90af-0fe552ca45c3.png">

**Comment by ankitnayan** [comment]
@makeavish @srikanthccv I think there might be some disparity on defining errors in metrics and traces here. Check the logic for errors at:
1. ServiceList page where Error% is calculated using traces
2. ServiceOverview page where Error% is calculated using APM metrics
3. ServiceMap definition of errors

Another suspect is whether 4xx is treated as error in traces but not in APM metrics. But I don't think that would affect this issue but we should check.

The `spanmetrics` processor should have an option whether to treat `4xx` as errors or not. NewRelic treats 4xx as errors and I saw a few companies getting confused due to this

**Comment by eugene-chernyshenko** [comment]
BTW my error code is 500 in this case

**Comment by eugene-chernyshenko** [comment]
SigNoz version is v0.16.0

**Comment by srikanthccv** [comment]
We have moved away from the HTTP status code error checking to span status error checking since the semantic interpretation of 4xx being the error depends on the span kind; for clients, under certain conditions, it is an error, but never for the server. The span status will be set based on that, so relying on the span status is consistent. I can't remember if the scale difference in the list vs. map page was mentioned previously. If there was no real reason we can make the service map * 100%.
