### ISSUE TITLE
(common): Formula support in query builder, same and across db's

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#2376]
- containing queries in the same data source
- containing queries across different data source

**Comment by srikanthccv** [comment]
Read [this](https://prometheus.io/docs/prometheus/latest/querying/operators/#one-to-one-vector-matches) and [this](https://www.robustperception.io/left-joins-in-promql/) to understand what does it mean to do `A + B` on two time series. The syntactic and semantics involved to evaluate the expression. The default mode is to do INNER JOIN of the result time series on the labels and evaluate `A.value + B.value` to produce the final result. Half way through the attempt of making a small table join like engine in query-service to evaluate expression I don't any benefit of this. And our attempt will probably buggy and needs maintenance. 

I would suggest letting ClickHouse do the expression evaluation and the job joining the result time series from the individual queries. Say there is a query `A` and `B` and formula `F1 = A/B`. The queries `A` and `B` can be evaluated independently. The current implementation for formulas today re-evaluates the `A` and `B` for the formula again which can be inefficient. We can make use of the [temporary tables](https://clickhouse.com/docs/en/sql-reference/statements/create/table/#temporary-tables) for the individual query and use them for the session of panel result. 

Let me know what do you think? I would like here people's thoughts on this since it came up during the last discussion to do this in query-service instead.
