### ISSUE TITLE
Otel clickhouse collector errors

### ISSUE THREAD

**Issue by itziklavon** [SigNoz/signoz#262]
## In what situation are you experiencing subpar performance?

i'm configuring otel collector with clickhouse(i've seen it is recommended to use kafka+druid, but trying it our with clickhouse)
when setting the grpc exporter and running small load test, seems like the client disconnects, where can i see the source code?
BTW, i think that instead configuring kafka + druid, you can use clickhouse buffer tables in order to export traces
when trying to run around 20-30 requests per second, it works pretty well, but when trying with around 50-60, the collector seems to disconnected every few seconds

ran my app with jaeger exporter(instead of otlp), and did not have any issue even when i had 500 requests per second

## Your Environment
 Mac

## Additional context
running pretty simple golang application using mysql, injecting traces to my web endpoint

will be happy to assist, but any guidance will be appriciated
also, when exposing the collector over here, and instruction on how to run it(not via docker) will be helpful

**Comment by ankitnayan** [comment]
@itziklavon thanks for detailing the issue.

1. Did you mean that you were able to ingest 500 rps using jaeger exporter in otel-collector and using jaeger to visualize
2. What is getting disconnected? Application to otel-collector connection or otel-collector to clickhouse connection?

> BTW, I think that instead configuring kafka + druid, you can use clickhouse buffer tables in order to export traces

Yes, also clickhouse has kafka integration which can further be used to handle scale.

**Comment by itzikiusa** [comment]
@ankitnayan 
1. yes, used jaeger exporter from: https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters (also with clickhouse as the datasource), and when tried to do the same using otlp exporter, was getting the errors
2. application to otel collector, got message that client is disconnecting, and few seconds after got message of 'no client', which eventually probably because the load go bigger and bigger got a log that indicates that the message sent is to big(greater then 4MB), i tried to adjust the setting in otel collector yaml, but without any success

**Comment by ankitnayan** [comment]
Do you mean, both settings are tested with SigNoz? Jaeger exporter works fine but otlp exporter shows `client is disconnecting` in high load?

> application to otel collector, got message that client is disconnecting, and few seconds after got message of 'no client', which eventually probably because the load go bigger and bigger got a log that indicates that the message sent is to big(greater then 4MB), i tried to adjust the setting in otel collector yaml, but without any success

Yes, since the traces were not delivered to otel-collector due to client disconnection, ultimately the batch size would have grown >4MB and thus the 2nd error.

**Comment by itzikiusa** [comment]
@ankitnayan 
no, jaeger exporter was used with jaeger as backend (can i use it with signoz? just to run similar test?)
otlp exporter was used with signoz as backend

**Comment by ankitnayan** [comment]
Got it...

>can i use it with signoz? just to run similar test?

Yes, since SigNoz uses otel-collector to receive traces which has jaeger receiver, you can use jaeger exporter at application. Also, the jaeger receiver is enabled by default at [this code line](https://github.com/SigNoz/signoz/blob/main/deploy/docker/clickhouse-setup/docker-compose.yaml#L60). You just need to open port 14268 in the machine where signoz is installed to start receiving data in jaeger format. 

Actually, the hotrod sample application that is used for the demo also sends data in jaeger format as seen in [this code line](https://github.com/SigNoz/signoz/blob/main/deploy/docker/clickhouse-setup/docker-compose.yaml#L79)

**Comment by itzikiusa** [comment]
@ankitnayan 
ok, will try the same (port is open)

i only removed the hotrod app and changed clickhouse endpoint

**Comment by itziklavon** [comment]
@ankitnayan 
getting the following error while trying to send traces via jaeger -
`2021/08/19 10:42:30 Post "http://localhost:14268/api/traces": EOF`

and port is up on docker:
`
62ea95baf1bf   signoz/otelcol:latest        "/otelcol --config=/…"   6 minutes ago   Up 6 minutes   0.0.0.0:1777->1777/tcp, :::1777->1777/tcp, 0.0.0.0:4317->4317/tcp, :::4317->4317/tcp, 0.0.0.0:14268->14268/tcp, :::14268->14268/tcp, 0.0.0.0:55679-55681->55679-55681/tcp, :::55679-55681->55679-55681/tcp, 0.0.0.0:8887->8888/tcp, :::8887->8888/tcp, 0.0.0.0:50328->13133/tcp, 0.0.0.0:50327->55678/tcp   clickhouse-setup_otel-collector_1
`

**Comment by ankitnayan** [comment]
@itziklavon How did you initialize the exporter? A code snippet would do.

I hope your application is running on the same machine as signoz.

**Comment by itziklavon** [comment]
@ankitnayan 
yes it does

BTW, got the same error with elastic APM (could not handle load of more then 50 transactions per second, and then started throwing errors that data sent is to big)

**Comment by itziklavon** [comment]
and for jaeger exporter:
```
	cfg := configDefault(config...)
	exporter, err := jaeger.New(jaeger.WithCollectorEndpoint(jaeger.WithEndpoint("http://localhost:14268/api/traces")))
	if err != nil {
		panic(err)
	}
	resources, err := resource.New(
		context.Background(),
		resource.WithAttributes(
			attribute.String("service.name", "wazdan"),
		),
	)
	if err != nil {
		panic(err)
	}
	//
	otel.SetTracerProvider(
		sdktrace.NewTracerProvider(
			sdktrace.WithSampler(sdktrace.AlwaysSample()),
			sdktrace.WithSyncer(exporter),
			sdktrace.WithResource(resources),
		),
	)

**Comment by itziklavon** [comment]
well, after reading a bit, this is the configuration i'm using now, almost without any errors(in period of 30 minutes, got 10 errors of disconnetion in total), my guess that the traces weren't sent in batches before, also used newer version of opentelemetry: (hope it will be helpful for those who had the same issues as me)
in general, the batch size almost did not change anything(default is 2048, might be good enogh)

```
	cfg := configDefault(config...)

	traceExporter, err := otlptracegrpc.New(context.Background(),
		otlptracegrpc.WithInsecure(),
		otlptracegrpc.WithEndpoint("localhost:4317"),
		otlptracegrpc.WithRetry(otlptracegrpc.RetryConfig{
			Enabled:         true,
			InitialInterval: 1 * time.Second,
			MaxInterval:     5 * time.Second,
			MaxElapsedTime:  10 * time.Minute,
		},
		),
	)

	if err != nil {
		panic(err)
	}
	resources, err := resource.New(
		context.Background(),
		resource.WithAttributes(
			attribute.String("service.name", "wazdan"),
		),
	)
	if err != nil {
		panic(err)
	}
	//
	bsp := sdktrace.NewBatchSpanProcessor(traceExporter, sdktrace.WithMaxExportBatchSize(10000), sdktrace.WithMaxQueueSize(10000))

	otel.SetTracerProvider(
		sdktrace.NewTracerProvider(
			sdktrace.WithSampler(sdktrace.AlwaysSample()),
			sdktrace.WithSpanProcessor(bsp),
			sdktrace.WithResource(resources),
		),
	)
