### ISSUE TITLE
[Logs] Use sum instead of count in rate aggregation

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#2726]
@srikanthccv  please add your thoughts here

**Comment by srikanthccv** [comment]
The numerator part of the rate is currently `count` regardless of the aggregate attribute. This will give incorrect results when the aggregate attribute is numeric. For example, say the user sends an attribute `items_in_cart` for each span/log record. When they want to see a rate of change of items in the cart for intervals, using count means 1 for 1 record irrespective of the `items_in_cart` value. This is unexpected.

Take the following data:

12.05 : Log(items_in_cart=5)
12.50: Log(items_in_cart=10)
01.20: Log(items_in_cart=1)
01.30: Log(items_in_cart=3)
01.44: Log(items_in_cart=1)
03.16: Log(items_in_cart=20)
04.32: Log(items_in_cart=42)


the rate of change here should be 15/60, 4/60, 20/60, 42/60 because the items in cart change over the time. The current implementation produces 2/60, 3/60, 1/60, 1/60 (this would have been fine for string attributes).

Let me know if this is clear.

**Comment by nityanandagohain** [comment]
SO @srikanthccv  you are suggesting that  in rate if the attribute is numeric then use sum(attribute)/60 which is similar to rate_sum ?

but shouldn't rate sum be used in that case ?

**Comment by srikanthccv** [comment]
Good point, you probably don't need to make any changes but I wonder if the end user understands them the same.

**Comment by nityanandagohain** [comment]
I think proper video tutorials will help for beginner users. I.e video explaining what different types of aggregation mean and how to use them in SigNoz.

Though the above is an addition to docs that we should write for our users.

**Comment by nityanandagohain** [comment]
Closing this, can open it if we have new thoughts.
