### ISSUE TITLE
Support for group by on value type

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2864]
Here's an example where group by value was required. Here value denotes different modes and the user wanted to count the number of series for each mode.
```
SELECT
    toStartOfInterval(toDateTime(intDiv(timestamp_ms, 1000)), toIntervalSecond(30)) AS ts,
    toString(value) AS mode,
    count() AS result
FROM signoz_metrics.distributed_samples_v2
GLOBAL INNER JOIN
(
    SELECT
        labels,
        fingerprint
    FROM signoz_metrics.distributed_time_series_v2
    WHERE metric_name = 'asterisk_endpoints_state'
) AS filtered_time_series USING (fingerprint)
WHERE (metric_name = 'asterisk_endpoints_state') 
AND (timestamp_ms between {{.SIGNOZ_START_TIME}} AND {{.SIGNOZ_END_TIME}})
AND (JSONExtractString(labels, 'host_name') IN {{.hostname}})
GROUP BY
    ts,
    mode
ORDER BY ts ASC
```

**Comment by srikanthccv** [comment]
"Value" type panel can only have one value, that is by design. We can't show multiple values. We don't allow group by for this reason. When there is more than one, you either have to use the list or table type depending on your use case.

**Comment by srikanthccv** [comment]
The requirement is valid but value type is not something that enables this. Table type is the solution.

**Comment by makeavish** [comment]
@srikanthccv I meant we need groupby on value. By value type I didn't mean value panel type, I meant value column which we use in results.
Reopening this.

**Comment by srikanthccv** [comment]
It's confusing and adds unnecessary complications. I still wouldn't suggest supporting this. Just because someone got their data wrong doesn't mean we should solve it with the builder. Supporting groupBy value here is like making the workaround solution to incorrect data as mainstream. Find a way to preprocess and restructure the data before it reaches the databases. If they need a such processor, we will try to provide a new process but I don't think we should support groupBy measurement value.
