### ISSUE TITLE
[Logs] Blank screen transition while scrolling new explorer page.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3044]
When we scroll in the new explorer page, there is a transition happening where the screen appears blank. We should remove that transition.

**Comment by srikanthccv** [comment]
You can disregard my opinion, but most infinite scroll interactions behave similarly like this to some extent when the number of pages you scroll past is non-trivial. You can notice this in social apps, but since we are not a social app, you can try using an observability vendor who has an inf scroll for logs.

1. Try viewing the logs for ten pages or so.
2. now, scroll up and down
3. you will notice the screen go white/ show the blanky behaviour.

**Comment by nityanandagohain** [comment]
I agree to that, when we have scrolled down 10's of pages and then scrolling hard should result result in a transition like that.

But when you are in the first page and just scrolling down a litte, those transitions becomes distractions.

**Comment by yeshev** [comment]
> When we scroll in the new explorer page, there is a transition happening where the screen appears blank. We should remove that transition.

@nityanandagohain Could you please record a video for that?

**Comment by nityanandagohain** [comment]
@yeshev  https://www.loom.com/share/accf549d1ffe48de9f16378e6b7a11b8
