### ISSUE TITLE
When there is no data for a row/column, is it possible to fill it with 0?

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#3277]

**Comment by vikrantgupta25** [comment]
Is filling the empty cells with `0` values the right thing to do? A column can either be a string type or an integer type hence filling all of them with `0` wouldn't be the best approach here. 

Also, let's say some column had a value of 0 then what happens? the user gets confused about whether the value was present or filled with `0` because it ideally had no value... 

Thoughts ? @srikanthccv

**Comment by vikrantgupta25** [comment]
closing as per discussion. CC :- @srikanthccv
