### ISSUE TITLE
[LOGS] Use materialized column if present for JSON search.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3553]
If user uses json key for search check if an attribute/materialized column is already present and then query based on that.

**Comment by srikanthccv** [comment]
Based on the changes in linked PRs, my understanding is that there will not be any `_` any more, and the keys will be added as it is. Did you think about the migration path for existing users? i.e. if they were sending an attribute `http.status_code` (or any namespaced attributes), the map no longer contains `http_status_code` but `http.status_code` and the same for the materialized columns. Alerts set up or dashboards created using the prior `_` separators and existing materialized columns will break as the keys change in the map? I believe this is disruptive change if there is no graceful path forward.

I imagine the dot/namespace separated keys will also be used as a part of the query builder, i.e. `http.method` from attributes. Do we expect that, or is it not under scope? If it is expected, can you check the logs query builder (and add tests) with them in group by/order by (anything other than where clause) and see if the query builder still prepares a valid query?

**Comment by nityanandagohain** [comment]
Yeah so I have tested different things like groupby order by with keys containing `.` and it's fine. One issue is this https://github.com/SigNoz/signoz/issues/3681 which needs to be resolved on the frontend.

Yeah the migration thing is a concerning one as it is kind of a entire revamp. Since for most of keys we don't know the actual name for running a migration without the context of the key. Apart from the common ones like `service_name`

**Comment by srikanthccv** [comment]
>Yeah so I have tested different things like groupby order by with keys containing . and it's fine.

This might be fine for the keys in the map, can you try materializing a column that has dots and then group by it? I am guessing it will break because you need to backtick around the key in group by, but the logs query builder doesn't do that.   I haven't checked it myself, so it could be wrong. I would like to see tests added to verify things, not just the old tests updated, because the assumptions you made at the time of writing them are no longer true. 

And I left my comments on the notion doc for one possible solution for graceful migration.

**Comment by nityanandagohain** [comment]
Thanks, I will update the tests and make sure to cover the things.

**Comment by nityanandagohain** [comment]
The actual implementation for supporting this in query service is still pending.
