### ISSUE TITLE
query-builder: support for promql sum function

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#3633]
Currently, `sum` operator in Query-Builder works very differently than that of PromQL `sum` function.

When converting a PromQL with `sum` function, it is not possible to get the exact same behaviour in query-builder.
We could introduce `PROM_SUM`.

**Comment by srikanthccv** [comment]
I would encourage adding the usecases/capabilities rather than the specific functions. We want to enable users to achieve certain tasks. The Prometheus query model is tightly coupled with their tsdb. What is supported there can't be exactly replicated here in the query builder. Please add what you were trying to achieve that couldn't be done.

**Comment by srikanthccv** [comment]
We won't be adding promql sum and that's not our goal. Depending on the context of the metric, one has to use `min/max/avg` etc.. as time aggregation and sum as space aggregation to achieve the same functionality. For example, to get the memory usage, one might want to avg for the time aggregation and then sum across the hosts. This is available under /v4/query_range.
