### ISSUE TITLE
[Epic]: New Logs Explorer - Bugs and Enhancements

### ISSUE THREAD

**Issue by YounixM** [SigNoz/signoz#4470]
Bug

1. [ ] 
2. [ ] 
3. [ ]

Enhancement Request

1. [ ]
2. [ ]
3. [ ]

**Comment by srikanthccv** [comment]
- The sticky save view at the bottom is very annoying to me. It hinders the ability to costume the logs at the bottom. 
- The text `Histogram` should be changed to `Bar chart`. It's not really a histogram. A histogram would show the data for bins i.e. the x-axis would be quantitative value instead. The `Bar chart` is the appropriate name.
- The text when a query run is in progress (i.e waiting for backend response) reads `This query had no results. Please edit your query and try again`. It should show the loader.
- I'd prefer a dumb message instead of fancy text `Just a bit of patience, just a little bit enough`. 
- Time series and table do not work.
- Overflow issues 
<img width="837" alt="Screenshot 2024-02-01 at 12 35 11 PM" src="https://github.com/SigNoz/signoz/assets/22846633/9ae57881-c335-4fa7-94d5-ac2e00cb8579">

**Comment by YounixM** [comment]
@GeekBoySupreme: Please check the UX related feedback above.

**Comment by YounixM** [comment]
3. Fixed - Will be available in next deployment
6.  Overflow issues  - This error is mostly in screen sizes less than 1024px. Handling the responsive. This should be in production as of now too.

**Comment by ankitnayan** [comment]
@YounixM is this completed?

**Comment by YounixM** [comment]
Yes @ankitnayan. This is completed. 

Let me close this.
