### ISSUE TITLE
`Continue without instrumentation` button is unresponsive when there are no sample app data

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#478]
## Bug description

`Continue without instrumentation` button is unresponsive when there are no sample app data

## Expected behavior

User should be allowed to explore the application even if no data is present from sample apps

## How to reproduce

1. Install via helm charts for clickhouse or just remove services from docker-compose
2. open the SigNoz Ui

https://share.getcloudapp.com/P8u8LkEL

## Version information 
* **Signoz version**: v0.5.2
* **Browser version**: Chrome 96.04
* **Your OS and version**: MacOS

**Comment by pranay01** [comment]
@pal-sig Did you get a chance to look into this?

**Comment by aryanshridhar** [comment]
Faced this issue today. This can be fixed by removing the extra check statement [here](https://github.com/SigNoz/signoz/blob/6f8b78bd97edccac2b81040e7671936e8b388846/frontend/src/container/MetricsTable/index.tsx#L36). (Though the `error` value is `true` because of `GET_INITIAL_APPLICATION_ERROR` but we still want the user to navigate our application)

**Comment by pranay01** [comment]
@pal-sig This is the issue which I was talking about. Thanks @aryanshridhar for pointing this out
