### ISSUE TITLE
Time selected changes from 5min to 30min/1hr or vice versa on clicking refresh button

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#481]
## Bug description

Time selected changes from 5min to 30min/1hr on clicking refresh 

## Expected behavior

Time selected shouldn't jump from 5min to 30min/1hr on clicking refresh button

## How to reproduce

1. Open SigNoz UI for the first time - confirm that the time selected is 5min in the /application page
2. Click any service and go to metrics page, confirm time selected is 5min
3. Press refresh button beside time selector, the time changes from 5min to 30min. 

_This is not repeating everytime though, so need to find exact scenario in which it reproduces_

## Version information 
* **Signoz version**: v0.5.2
* **Browser version**: Chrome 96.0.4
* **Your OS and version**: macOS Monterey

## Additional context

https://share.getcloudapp.com/X6ubmGKE

**Comment by Deeprana12** [comment]
Can I work on this? @pranay01

**Comment by pranay01** [comment]
Sure @Deeprana12 

Though I was not able to consistently reproduce this - so first check if it is reproducing consistently

**Comment by Deeprana12** [comment]
from /application when time is selected to 5min, then after when I click on the frontend it remains 5min but in customer, driver or route it changes to 30min. Is this the issue you are talking about @pranay01?

**Comment by pranay01** [comment]
On /application/frontend - 1hr is selected - but on clicking refresh it goes to 5min. 
At around 0:35sec in the video

Updated the title also.

**Comment by Deeprana12** [comment]
when we click on any application like a /customer, /drive, /route the default value we'll get is 30min except /application(for this 5min) because when the page first redirect to a particular page the default value it's getting is 30min because of the below code snippet written in typescript so for the solution: we can change time to 5min for all routes so whenever we click on any application it will give use default time as 5 min after changing it remains same for a refresh.
I think this should be the problem @pranay01 

![image](https://user-images.githubusercontent.com/69518599/145628599-8192cae2-d1a4-44e5-b8a8-89546a4d4178.png)

**Comment by Deeprana12** [comment]
Hey @pranay01 

Here are the things that I understand from the code:

1. While rendering these pages for the first time we are getting values from a function below and here problems occur.

![Screenshot 2021-12-11 232008](https://user-images.githubusercontent.com/69518599/145686637-b5ebb131-435b-48b8-b132-d0cc5b024a83.png)

2. but after rendering when we change it to any time like (1 hr etc) and refresh after that it works perfectly because at that time we are storing the values in the localStorage and on refresh we are retrieving from it as well.

so for the solution of this,
On rendering, Instead of getting these values from the function, we can set localStorage with default values(like 5min) for all pages(like /route, /customer, etc) so this issue will be resolved.

**Comment by pranay01** [comment]
@pal-sig Can you check this?

**Comment by pal-sig** [comment]
> Hey @pranay01
> 
> Here are the things that I understand from the code:
> 
> 1. While rendering these pages for the first time we are getting values from a function below and here problems occur.
> 
> ![Screenshot 2021-12-11 232008](https://user-images.githubusercontent.com/69518599/145686637-b5ebb131-435b-48b8-b132-d0cc5b024a83.png)
> 
> 2. but after rendering when we change it to any time like (1 hr etc) and refresh after that it works perfectly because at that time we are storing the values in the localStorage and on refresh we are retrieving from it as well.
> 
> so for the solution of this, On rendering, Instead of getting these values from the function, we can set localStorage with default values(like 5min) for all pages(like /route, /customer, etc) so this issue will be resolved.

@Deeprana12 did not get this one

**Comment by Deeprana12** [comment]
Ok, let me prepare a short video describing the problem and solution @pal-sig

**Comment by pal-sig** [comment]
Sure

**Comment by Deeprana12** [comment]
Here I've created some short videos because video-limit is getting decreasing & they can't fit in one video so sorry for the inconvenience.
Part1 - https://share.getcloudapp.com/jkuE9AoO
Part2 - https://share.getcloudapp.com/llukP7Dp
Part3 - https://share.getcloudapp.com/llukP7rn

In short - If we store default values in localStorage then all the errors will be resolved because eventually, we are storing it afterward.

**Comment by Deeprana12** [comment]
Here I've created some short videos because video-limit is getting decreasing & they can't fit in one video so sorry for the inconvenience.
Part1 - https://share.getcloudapp.com/jkuE9AoO
Part2 - https://share.getcloudapp.com/llukP7Dp
Part3 - https://share.getcloudapp.com/llukP7rn

In short - If we store default values in localStorage then all the errors will be resolved because eventually, we are storing it afterward. @pal-sig

**Comment by Deeprana12** [comment]
What do you say @pal-sig?

**Comment by Deeprana12** [comment]
should I generate the PR or not @pal-sig?

**Comment by pal-sig** [comment]
Hi @Deeprana12 
Thank for taking up the issue 

and yes i think creating all the default values in the local-storage would help here

**Comment by pal-sig** [comment]
> should I generate the PR or not @pal-sig?

please go for it :-D

**Comment by pal-sig** [comment]
> should I generate the PR or not @pal-sig?

also do handle the edge cases ... when we input the value apart from the accepted value .. do take from the default option value

**Comment by Deeprana12** [comment]
Yes, @pal-sig. Done with the PR. looking forward to more contributions to signoz 😉.

**Comment by pal-sig** [comment]
@Deeprana12 please update the PR there are certain issue that need to be resolved

**Comment by pranay01** [comment]
Closing issue as this is fixed now
