### ISSUE TITLE
Better representation of graphs for longer time periods like 1 day/week

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#552]
Users might want to investigate the data points for longer duration like `1 day` or `1 week`. Depending on the business use case, users might want to investigate how a particular request is performing over a day/week to see any deviation from the norm.

Currently our graphs are not redable for the longer duration

<img width="1230" alt="Screenshot 2021-12-21 at 4 12 20 PM" src="https://user-images.githubusercontent.com/83692067/146916727-cc9a54b1-b527-4d8a-8d82-18e8b34f5c41.png">

Week's graph does not have any dates in it, just timestamps in `hh:mm` format which will be confusing to the user.

<img width="1233" alt="Screenshot 2021-12-21 at 4 13 23 PM" src="https://user-images.githubusercontent.com/83692067/146916880-7144cdd2-9999-48bc-80e2-c79d00ac28a7.png">

**Comment by ankit01-oss** [comment]
To clarify, when I say better representation of graphs, it's not just about having timestamps with days (Monday, Tuesday) in it on the x-axis.

The graph should help users to identify spikes or outliers in any time-frame chosen, so aggregated data for a day or any longer time period can help.

**Comment by pal-sig** [comment]
thanks @ankit01-oss for the clarification. one point i would like to point data also should be less

**Comment by pal-sig** [comment]
@pranay01 let me know your thoughts over this one

**Comment by pranay01** [comment]
@ankitnayan Should the backend APIs also be modified for this? Because high granularity of data may bot be very relevant and would make the graph look cluttered. It is also not helpful to the users.

For example - 
- if time period is less than 1hr, granularity may 1 min
- if time period is 1hr - 6hr, then granularity may be 5 min ( 60 data points)
- For 1 day, granularity may be 10 mins - 144 data points
- and so on..

We can decide on exact time intervals for each data point, but I think it should change with total data duration

This will also make graph components load faster as @pal-sig mentions
