### ISSUE TITLE
Cleaning up Sign in flow

### ISSUE THREAD

**Issue by GeekBoySupreme** [SigNoz/signoz#5737]
This issue deals with cleaning up the sign in flow for a user entering the SigNoz tenant for the first time and setting up their workspace.

Find the designs [here](https://www.figma.com/design/Zz8GpUHSpwnl9zNXyeZZaO/Onboarding?node-id=2116-23826&t=8GQZb8rCo9TtmdoZ-1)
Prototype ⎯ [here](https://www.figma.com/proto/Zz8GpUHSpwnl9zNXyeZZaO/Onboarding?page-id=2%3A351&node-id=2116-10222&viewport=382%2C-1320%2C0.27&t=8zwQVgidlYSYBkC1-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2116%3A10222&show-proto-sidebar=1&hide-ui=1)

https://github.com/user-attachments/assets/1110fda4-6a80-44aa-9760-3b0fdfaba49c

Note that the screen after `Invite your team` has not been finalized yet. We are still working on the Connect a data source story.

**Comment by GeekBoySupreme** [comment]
@pranay01 @ankit01-oss take a look.

**Comment by GeekBoySupreme** [comment]
@YounixM for the password strength, feel free to use any externally available open source script.

**Comment by ankit01-oss** [comment]
Notes:

Should we also have others as an input field?
<img width="673" alt="Screenshot 2024-08-21 at 5 56 31 PM" src="https://github.com/user-attachments/assets/36827a82-379f-47fb-aaac-238e330186f9">

We can have departments rather than designation. Designation might be limited to cover roles:

Something like this, and then we can assign scores based on department. For our case, we can have fields like devops, sre, etc.
<img width="584" alt="Screenshot 2024-08-21 at 6 08 02 PM" src="https://github.com/user-attachments/assets/2675f648-da05-4631-99d8-c13bff7f7fab">



Another way to judge seniority(just a suggestion)
<img width="525" alt="Screenshot 2024-08-21 at 6 10 35 PM" src="https://github.com/user-attachments/assets/c1917315-b3a2-4d65-a0c7-82776a1c3cd1">


Below question can be re-phrased(sounds like the person is employing):
How many employees do you have? --> How large is your company?

Please add this question. We don't want to enable intercom for services co. We will have to monitor how many fill this correctly.

**What kind of company is it?**
Dropdown options: Product Company, IT Services, Product & Services  - @pranay01 Please suggest any improvements.



Need answers for these too to decide ICP score.@GeekBoySupreme 
<img width="623" alt="Screenshot 2024-08-21 at 6 24 48 PM" src="https://github.com/user-attachments/assets/df7f92ff-1a48-4255-82de-278ded3506c9">

**Comment by pranay01** [comment]
@makeavish 

Do you currently use any observability/monitoring tool?
- [ ] No
- [ ] Yes

If yes, give them a selection of tools
- [ ] AWS Cloudwatch
- [ ] DataDog
- [ ] New Relic
- [ ] Grafana / Prometheus
- [ ] Azure App monitor
- [ ] GCP native  o11y tools
- [ ] Honeycomb
- [ ] Others (Write in text box)

Familiarity with OpenTelemetry?
- [ ] Not heard
- [ ] Heard
- [ ] Experimented
- [ ] Implemented in your org

Scale? (How to ideas)
- Logs (number of GBs) - Input number box
- Metrics (Number of Hosts) - Input number box
- Number of services - Input number box
- Don't have any idea

Why are you looking for 
- [ ] Cost
- [ ] Interest in Otel Native stack
- [ ] All in one 
- [ ] Others [Write yourself]

**Comment by pranay01** [comment]
3 and 4 should not be blocking

**Comment by makeavish** [comment]
List of events: https://www.notion.so/signoz/Analytics-events-list-e43794709fc94dd19ff650b56806a5d2?pvs=4#847375fc59eb461b9f04a3034bd4bcaa

**Comment by GeekBoySupreme** [comment]
Find the prototype with updated questionnaire [here](https://www.figma.com/proto/Zz8GpUHSpwnl9zNXyeZZaO/Onboarding?page-id=2%3A351&node-id=2166-5111&viewport=348%2C-583%2C0.12&t=SuM0j2qEv6IqWVue-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2166%3A5111&show-proto-sidebar=1&hide-ui=1)

@ankit01-oss @pranay01 I tweaked the copy text a little bit in the above questions. Take a look if it looks fine.

Find the Figma board [here](https://www.figma.com/design/Zz8GpUHSpwnl9zNXyeZZaO/Onboarding?node-id=2166-5111&t=ftr062bint4aFxAM-1)

**Comment by GeekBoySupreme** [comment]
Broke down the questions into 2 screens -

https://github.com/user-attachments/assets/892819ae-e634-43c5-9fa9-ca2987e53e02

Effect on clicking the `Other` button

https://github.com/user-attachments/assets/1674203d-512a-4935-93ba-38dd2421c648

**Comment by YounixM** [comment]
UI Ready - Pending on API's

**Comment by YounixM** [comment]
Part 1 is merged ✅

**Comment by YounixM** [comment]
Part 2 - Merged ✅
