### ISSUE TITLE
Update react-router-dom

### ISSUE THREAD

**Issue by YounixM** [SigNoz/signoz#6167]
Update react-router-dom in signoz repo

**Comment by ahmadshaheer** [comment]
Instead of attempting to upgrade react-router to v6 and update all of our code simultaneously we'll use the backwards compatibility package to allow for a gradual transition.

Upgrading strategy -> https://www.notion.so/Upgrading-react-router-to-v6-12cc8e7d1f5c80a3b66ad474d7478050#4b3251525fa144e69d5442ec7aaa9bad
