### ISSUE TITLE
feat: Alert Channel For Email

### ISSUE THREAD

**Issue by jhaan21** [SigNoz/signoz#623]
## Is your feature request related to a problem?

No

## Describe the solution you'd like

The only alert channels available is through slack. I would like to be able to at least send a notification to multiple parties about the alert.

## Describe alternatives you've considered

Forcing my team onto slack but I am also unsure if customers would be willing to do this as well

## Additional context

<img width="986" alt="Screen Shot 2022-01-18 at 7 49 59 AM" src="https://user-images.githubusercontent.com/13485996/149940625-eb02ff30-d636-47cd-bafd-51a31ea94742.png">

**Comment by pranay01** [comment]
@jhaan21 Thanks for opening this issue. Just to understand your use case better, do you also want your customers to receive alerts about your system metrics from SigNoz?

**Comment by jhaan21** [comment]
@pranay01 No problem. I believe there is an opportunity for both internal and customers wanting to be alerted if we have a service down. I think if you can just do multiple emails that will work for both internal and external.

**Comment by meyvan** [comment]
wouldnt it be better to build a generic webhook input ? and do whatever you want with it when you receive an event. I understand that is extremely important but having a webhook  would solve most of the customer's problems since they can build it themselves and allows the team to focus to pushing other features for the time being

**Comment by pranay01** [comment]
thats a good point @meyvan  Would enabling webhook's also add email as a channel?

**Comment by meyvan** [comment]
Yup, infact you dont even need slack as a channel, since the data is transferred on a per-event basis, the webhook is responsible for transferring internally or externally to any systems they prefer including but not limited slack, email, another datawarehouse for compliance storage etc... From signoz point only webhook should be supported. No need to unneccesarily maintain intregations. The sprint cycle of the team then be focussed on addressing immediate issues

**Comment by sriv** [comment]
hi, just wanted to check if this approach of allowing payloads in a webhook is being considered and worked upon? Happy to submit a PR. Please share any hints that may help here.
