### ISSUE TITLE
unable to click other pages when logging in on frontend

### ISSUE THREAD

**Issue by mdg215199** [SigNoz/signoz#648]
## Bug description
run kubectl -n platform port-forward svc/signoz-frontend 3000:3000

log in, page takes you to:
http://localhost:3000/application

There is a video I can watch, but the menu item on the left is turned off, so I cant go to any page.  There might be an obvious that I'm missing, but I wasted about five or ten minutes trying to figure out how to activate the buttons.  Finally, i just looked in code to find another routing, like:
http://localhost:3000/traces

which i was able to get a page up, and change other pages

*Please describe.*  
not necessary, explained in "Bug description"

## Expected behavior
When I login, and go to /application, I shoudl be able to go to other pages

## How to reproduce
Read "Bug description" area

1.
2.
3.

## Version information 
* **Signoz version**: 0.5
* **Browser version**: firefox (chrome doesnt work... see ticket 647)
* **Your OS and version**: ubuntu 21.04

**Comment by pranay01** [comment]
hey @mdg215199 thanks for raising the issue. 

@ankitnayan Could this be because helm charts were not pointing to latest version of SigNoz

@mdg215199 We recently updated instructions for deploying via Helm - https://signoz.io/docs/deployment/helm_chart/ Can you check if using this solves the issue?

**Comment by makeavish** [comment]
Stale bug.
Closing it.
